# coding=utf-8
HOSTNAME = 'localhost'
DATABASE = 'eportfolio'
USERNAME = 'admin'
PASSWORD = 'admin'
DB_URI = 'mysql://{}:{}@{}/{}'.format(
    USERNAME, PASSWORD, HOSTNAME, DATABASE)

NODE_URL = "http://node.deviceproof.org:14265"
SEED = "RBYYYKDIUDXV9Z9FQPFJSA9QQIGFZAS9XXAWHSDPPXYR9ULXZWYNQSOOYHOXSNXEORWGRIQXXINRHKTCU"
DEPTH = 7
MIN_WEIGHT_MAGNITUDE = 14